package com.abyz.infotech.warroomapp.greenDAO.sqlite;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        TABLE_USERDao.createTable(db, ifNotExists);
        TABLE_USER_PROFILESDao.createTable(db, ifNotExists);
        TABLE_USER_TYPEDao.createTable(db, ifNotExists);
        TABLE_EVENTDao.createTable(db, ifNotExists);
        TABLE_EVENT_SPEAKERDao.createTable(db, ifNotExists);
        TABLE_SPEAKERDao.createTable(db, ifNotExists);
        TABLE_TASK_ALLOTMENTDao.createTable(db, ifNotExists);
        TABLE_EVENT_TASKDao.createTable(db, ifNotExists);
        TABLE_TASKDao.createTable(db, ifNotExists);
        TABLE_TASK_CATEGORYDao.createTable(db, ifNotExists);
        TABLE_CATEGORYDao.createTable(db, ifNotExists);
        TABLE_EVENT_COORDINATERDao.createTable(db, ifNotExists);
        TABLE_STATUSDao.createTable(db, ifNotExists);
        TABLE_LOCATION_AREADao.createTable(db, ifNotExists);
        TABLE_DISTRICTDao.createTable(db, ifNotExists);
        TABLE_STATEDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        TABLE_USERDao.dropTable(db, ifExists);
        TABLE_USER_PROFILESDao.dropTable(db, ifExists);
        TABLE_USER_TYPEDao.dropTable(db, ifExists);
        TABLE_EVENTDao.dropTable(db, ifExists);
        TABLE_EVENT_SPEAKERDao.dropTable(db, ifExists);
        TABLE_SPEAKERDao.dropTable(db, ifExists);
        TABLE_TASK_ALLOTMENTDao.dropTable(db, ifExists);
        TABLE_EVENT_TASKDao.dropTable(db, ifExists);
        TABLE_TASKDao.dropTable(db, ifExists);
        TABLE_TASK_CATEGORYDao.dropTable(db, ifExists);
        TABLE_CATEGORYDao.dropTable(db, ifExists);
        TABLE_EVENT_COORDINATERDao.dropTable(db, ifExists);
        TABLE_STATUSDao.dropTable(db, ifExists);
        TABLE_LOCATION_AREADao.dropTable(db, ifExists);
        TABLE_DISTRICTDao.dropTable(db, ifExists);
        TABLE_STATEDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(TABLE_USERDao.class);
        registerDaoClass(TABLE_USER_PROFILESDao.class);
        registerDaoClass(TABLE_USER_TYPEDao.class);
        registerDaoClass(TABLE_EVENTDao.class);
        registerDaoClass(TABLE_EVENT_SPEAKERDao.class);
        registerDaoClass(TABLE_SPEAKERDao.class);
        registerDaoClass(TABLE_TASK_ALLOTMENTDao.class);
        registerDaoClass(TABLE_EVENT_TASKDao.class);
        registerDaoClass(TABLE_TASKDao.class);
        registerDaoClass(TABLE_TASK_CATEGORYDao.class);
        registerDaoClass(TABLE_CATEGORYDao.class);
        registerDaoClass(TABLE_EVENT_COORDINATERDao.class);
        registerDaoClass(TABLE_STATUSDao.class);
        registerDaoClass(TABLE_LOCATION_AREADao.class);
        registerDaoClass(TABLE_DISTRICTDao.class);
        registerDaoClass(TABLE_STATEDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
