package com.abyz.infotech.warroomapp.greenDAO.sqlite;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.abyz.infotech.warroomapp.model.TABLE_USER_PROFILES;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table TABLE__USER__PROFILES.
*/
public class TABLE_USER_PROFILESDao extends AbstractDao<TABLE_USER_PROFILES, Long> {

    public static final String TABLENAME = "TABLE__USER__PROFILES";

    /**
     * Properties of entity TABLE_USER_PROFILES.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_ID");
        public final static Property UserProfId = new Property(1, Integer.class, "userProfId", false, "USER_PROF_ID");
        public final static Property UserProfUsrId = new Property(2, Integer.class, "userProfUsrId", false, "USER_PROF_USR_ID");
        public final static Property UserProfUsrTypeId = new Property(3, Integer.class, "userProfUsrTypeId", false, "USER_PROF_USR_TYPE_ID");
        public final static Property UserStateID = new Property(4, Integer.class, "userStateID", false, "USER_STATE_ID");
        public final static Property TimeStamp = new Property(5, Long.class, "timeStamp", false, "TIME_STAMP");
    };


    public TABLE_USER_PROFILESDao(DaoConfig config) {
        super(config);
    }
    
    public TABLE_USER_PROFILESDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TABLE__USER__PROFILES' (" + //
                "'_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "'USER_PROF_ID' INTEGER UNIQUE ," + // 1: userProfId
                "'USER_PROF_USR_ID' INTEGER ," + // 2: userProfUsrId
                "'USER_PROF_USR_TYPE_ID' INTEGER ," + // 3: userProfUsrTypeId
                "'USER_STATE_ID' INTEGER," + // 4: userStateID
                "'TIME_STAMP' LONG);"); // 5: timeStamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TABLE__USER__PROFILES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TABLE_USER_PROFILES entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        Integer userProfId = entity.getUserProfId();
        if (userProfId != null) {
            stmt.bindLong(2, userProfId);
        }
 
        Integer userProfUsrId = entity.getUserProfUsrId();
        if (userProfUsrId != null) {
            stmt.bindLong(3, userProfUsrId);
        }
 
        Integer userProfUsrTypeId = entity.getUserProfUsrTypeId();
        if (userProfUsrTypeId != null) {
            stmt.bindLong(4, userProfUsrTypeId);
        }
 
        Integer userStateID = entity.getUserStateID();
        if (userStateID != null) {
            stmt.bindLong(5, userStateID);
        }

        Long timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindLong(6, timeStamp);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TABLE_USER_PROFILES readEntity(Cursor cursor, int offset) {
        TABLE_USER_PROFILES entity = new TABLE_USER_PROFILES( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // userProfId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // userProfUsrId
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // userProfUsrTypeId
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // userStateID
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // timeStamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TABLE_USER_PROFILES entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserProfId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setUserProfUsrId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setUserProfUsrTypeId(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setUserStateID(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setTimeStamp(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TABLE_USER_PROFILES entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TABLE_USER_PROFILES entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
