package com.abyz.infotech.warroomapp.greenDAO.sqlite;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.abyz.infotech.warroomapp.model.TABLE_CATEGORY;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table TABLE__CATEGORY.
*/
public class TABLE_CATEGORYDao extends AbstractDao<TABLE_CATEGORY, Long> {

    public static final String TABLENAME = "TABLE__CATEGORY";

    /**
     * Properties of entity TABLE_CATEGORY.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_ID");
        public final static Property CatId = new Property(1, Integer.class, "catId", false, "CAT_ID");
        public final static Property CatName = new Property(2, String.class, "catName", false, "CAT_NAME");
        public final static Property CatStatusId = new Property(3, Integer.class, "catStatusId", false, "CAT_STATUS_ID");
        public final static Property TimeStamp = new Property(4, Long.class, "timeStamp", false, "TIME_STAMP");
    };


    public TABLE_CATEGORYDao(DaoConfig config) {
        super(config);
    }
    
    public TABLE_CATEGORYDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TABLE__CATEGORY' (" + //
                "'_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "'CAT_ID' INTEGER UNIQUE ," + // 1: catId
                "'CAT_NAME' TEXT," + // 2: catName
                "'CAT_STATUS_ID' INTEGER," + // 3: catStatusId
                "'TIME_STAMP' INTEGER);"); // 4: timeStamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TABLE__CATEGORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TABLE_CATEGORY entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        Integer catId = entity.getCatId();
        if (catId != null) {
            stmt.bindLong(2, catId);
        }
 
        String catName = entity.getCatName();
        if (catName != null) {
            stmt.bindString(3, catName);
        }
 
        Integer catStatusId = entity.getCatStatusId();
        if (catStatusId != null) {
            stmt.bindLong(4, catStatusId);
        }
 
        Long timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindLong(5, timeStamp);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TABLE_CATEGORY readEntity(Cursor cursor, int offset) {
        TABLE_CATEGORY entity = new TABLE_CATEGORY( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // catId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // catName
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // catStatusId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // timeStamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TABLE_CATEGORY entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCatId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setCatName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCatStatusId(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setTimeStamp(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TABLE_CATEGORY entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TABLE_CATEGORY entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
