package com.abyz.infotech.warroomapp.greenDAO.sqlite;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.abyz.infotech.warroomapp.model.TABLE_TASK_CATEGORY;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table TABLE__TASK__CATEGORY.
*/
public class TABLE_TASK_CATEGORYDao extends AbstractDao<TABLE_TASK_CATEGORY, Long> {

    public static final String TABLENAME = "TABLE__TASK__CATEGORY";

    /**
     * Properties of entity TABLE_TASK_CATEGORY.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_ID");
        public final static Property TcId = new Property(1, Integer.class, "tcId", false, "TC_ID");
        public final static Property TcTskId = new Property(2, Integer.class, "tcTskId", false, "TC_TSK_ID");
        public final static Property TcCatId = new Property(3, Integer.class, "tcCatId", false, "TC_CAT_ID");
        public final static Property TcStatusId = new Property(4, Integer.class, "tcStatusId", false, "TC_STATUS_ID");
        public final static Property TimeStamp = new Property(5, Long.class, "timeStamp", false, "TIME_STAMP");
    };


    public TABLE_TASK_CATEGORYDao(DaoConfig config) {
        super(config);
    }
    
    public TABLE_TASK_CATEGORYDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TABLE__TASK__CATEGORY' (" + //
                "'_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "'TC_ID' INTEGER UNIQUE ," + // 1: tcId
                "'TC_TSK_ID' INTEGER," + // 2: tcTskId
                "'TC_CAT_ID' INTEGER," + // 3: tcCatId
                "'TC_STATUS_ID' INTEGER," + // 4: tcStatusId
                "'TIME_STAMP' INTEGER);"); // 5: timeStamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TABLE__TASK__CATEGORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TABLE_TASK_CATEGORY entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        Integer tcId = entity.getTcId();
        if (tcId != null) {
            stmt.bindLong(2, tcId);
        }
 
        Integer tcTskId = entity.getTcTskId();
        if (tcTskId != null) {
            stmt.bindLong(3, tcTskId);
        }
 
        Integer tcCatId = entity.getTcCatId();
        if (tcCatId != null) {
            stmt.bindLong(4, tcCatId);
        }
 
        Integer tcStatusId = entity.getTcStatusId();
        if (tcStatusId != null) {
            stmt.bindLong(5, tcStatusId);
        }
 
        Long timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindLong(6, timeStamp);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TABLE_TASK_CATEGORY readEntity(Cursor cursor, int offset) {
        TABLE_TASK_CATEGORY entity = new TABLE_TASK_CATEGORY( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // tcId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // tcTskId
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // tcCatId
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // tcStatusId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // timeStamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TABLE_TASK_CATEGORY entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTcId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setTcTskId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setTcCatId(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setTcStatusId(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setTimeStamp(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TABLE_TASK_CATEGORY entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TABLE_TASK_CATEGORY entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
