package com.abyz.infotech.warroomapp.common;

public enum EVENT_BUS_MESSAGE {
    LOGIN_WEBSERVICE,
    INVALID_CREDENTIALS,
    INVALID,
    WEBSERVICE_DOWN,
    INVALID_PASSWORD,
    OTP_DELIVERED,
    OTP_CONFIRMED,
    PASSWORD_CHANGE_SUCCESSFUL,
    UNABLE_TO_CHANGE_PASSWORD,
    EVENT_WEBSERVICE,
    MOBILENO_CHANGE_SUCCESSFUL,
    UNABLE_TO_CHANGE_MOBILENO,
    MOBILE_NO_CHANGE_SUCCESSFUL,
    TASK_STATUS_WEBSERVICE,
    TASK_WEBSERVICE,
    EVENTTASKALLOTMENT_WEBSERVICE,
    EVENTTASKADD_WEBSERVICE,
    FEEDBACK_WEBSERVICE
}
