package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__USER.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_USER {

    private Long id;

    @SerializedName("userid")
    @Expose
    private Integer usrId;

    @SerializedName("user_name")
    @Expose
    private String usrName;

    @SerializedName("user_gender")
    @Expose
    private String usrGender;

    @SerializedName("user_mobile")
    @Expose
    private String usrMobile;

    @SerializedName("user_address")
    @Expose
    private String usrAddress;

    @SerializedName("user_image")
    @Expose
    private String usrImage;

    @SerializedName("user_status")
    @Expose
    private Integer usrState;

    @SerializedName("user_timestamp")
    @Expose
    private Long timeStamp;

    @SerializedName("depart_id")
    @Expose
    private Integer usrDepartId;
    @SerializedName("depart_name")
    @Expose
    private String usrDepartName;

    public Integer getUserLocareaid() {
        return userLocareaid;
    }

    public void setUserLocareaid(Integer userLocareaid) {
        this.userLocareaid = userLocareaid;
    }

    @SerializedName("user_locareaid")
    @Expose
    private Integer userLocareaid;

    public TABLE_USER() {
    }

    public TABLE_USER(Long id) {
        this.id = id;
    }

    public TABLE_USER(Long id, Integer usrId, String usrName, String usrGender, String usrMobile, String usrAddress, String usrImage, Integer usrState, Long timeStamp, Integer usrDepartId, String usrDepartName, Integer userLocareaid) {
        this.id = id;
        this.usrId = usrId;
        this.usrName = usrName;
        this.usrGender = usrGender;
        this.usrMobile = usrMobile;
        this.usrAddress = usrAddress;
        this.usrImage = usrImage;
        this.usrState = usrState;
        this.timeStamp = timeStamp;
        this.usrDepartId = usrDepartId;
        this.usrDepartName = usrDepartName;
        this.userLocareaid = userLocareaid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUsrId() {
        return usrId;
    }

    public void setUsrId(Integer usrId) {
        this.usrId = usrId;
    }

    public String getUsrName() {
        return usrName;
    }

    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }

    public String getUsrGender() {
        return usrGender;
    }

    public void setUsrGender(String usrGender) {
        this.usrGender = usrGender;
    }

    public String getUsrMobile() {
        return usrMobile;
    }

    public void setUsrMobile(String usrMobile) {
        this.usrMobile = usrMobile;
    }

    public String getUsrAddress() {
        return usrAddress;
    }

    public void setUsrAddress(String usrAddress) {
        this.usrAddress = usrAddress;
    }

    public String getUsrImage() {
        return usrImage;
    }

    public void setUsrImage(String usrImage) {
        this.usrImage = usrImage;
    }

    public Integer getUsrState() {
        return usrState;
    }

    public void setUsrState(Integer usrState) {
        this.usrState = usrState;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Integer getUsrDepartId() {
        return usrDepartId;
    }

    public void setUsrDepartId(Integer usrDepartId) {
        this.usrDepartId = usrDepartId;
    }

    public String getUsrDepartName() {
        return usrDepartName;
    }

    public void setUsrDepartName(String usrDepartName) {
        this.usrDepartName = usrDepartName;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }
}
