package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__EVENT__COORDINATER.
 */

import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_EVENT_COORDINATER {

    private Long _id;

    @SerializedName("ec_id")
    @Expose
    private Integer ecId;

    @SerializedName("ec_usr_id")
    @Expose
    private Integer ecUserId;

    @SerializedName("ec_evnt_id")
    @Expose
    private Integer ecEventId;

    @SerializedName("ec_evnt_name")
    @Expose
    private String ecEventName;

    @SerializedName("ec_topic")
    @Expose
    private String ecTopic;

    @SerializedName("ec_desc")
    @Expose
    private String ecDesc;

    @SerializedName("ec_mobile_no")
    @Expose
    private String ecUserMobileNo;

    @SerializedName("user_name")
    @Expose
    private String ecUserName;

    @SerializedName("ec_status_id")
    @Expose
    private Integer ecStatusId;

    @SerializedName("ec_timestamp")
    @Expose
    private Long timeStamp;

    public TABLE_EVENT_COORDINATER() {
    }

    public TABLE_EVENT_COORDINATER(Long _id) {
        this._id = _id;
    }

    public TABLE_EVENT_COORDINATER(Long _id, Integer ecId, Integer ecUserId, Integer ecEventId, String ecEventName, String ecTopic, String ecDesc, String ecUserMobileNo, String ecUserName, Integer ecStatusId, Long timeStamp) {
        this._id = _id;
        this.ecId = ecId;
        this.ecUserId = ecUserId;
        this.ecEventId = ecEventId;
        this.ecEventName = ecEventName;
        this.ecTopic = ecTopic;
        this.ecDesc = ecDesc;
        this.ecUserMobileNo = ecUserMobileNo;
        this.ecUserName = ecUserName;
        this.ecStatusId = ecStatusId;
        this.timeStamp = timeStamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getEcId() {
        return ecId;
    }

    public void setEcId(Integer ecId) {
        this.ecId = ecId;
    }

    public Integer getEcUserId() {
        return ecUserId;
    }

    public void setEcUserId(Integer ecUserId) {
        this.ecUserId = ecUserId;
    }

    public Integer getEcEventId() {
        return ecEventId;
    }

    public void setEcEventId(Integer ecEventId) {
        this.ecEventId = ecEventId;
    }

    public String getEcEventName() {
        return ecEventName;
    }

    public void setEcEventName(String ecEventName) {
        this.ecEventName = ecEventName;
    }

    public String getEcTopic() {
        return ecTopic;
    }

    public void setEcTopic(String ecTopic) {
        this.ecTopic = ecTopic;
    }

    public String getEcDesc() {
        return ecDesc;
    }

    public void setEcDesc(String ecDesc) {
        this.ecDesc = ecDesc;
    }

    public String getEcUserMobileNo() {
        return ecUserMobileNo;
    }

    public void setEcUserMobileNo(String ecUserMobileNo) {
        this.ecUserMobileNo = ecUserMobileNo;
    }

    public String getEcUserName() {
        return ecUserName;
    }

    public void setEcUserName(String ecUserName) {
        this.ecUserName = ecUserName;
    }

    public Integer getEcStatusId() {
        return ecStatusId;
    }

    public void setEcStatusId(Integer ecStatusId) {
        this.ecStatusId = ecStatusId;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }


    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
