package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__USER__PROFILES.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_USER_PROFILES {

    private Long _id;

    @SerializedName("userprof_id")
    @Expose
    private Integer userProfId;

    @SerializedName("userprof_usrid")
    @Expose
    private Integer userProfUsrId;

    @SerializedName("userproftype_id")
    @Expose
    private Integer userProfUsrTypeId;

    @SerializedName("userprof_status")
    @Expose
    private Integer userStateID;

    @SerializedName("userprof_timestamp")
    @Expose
    private Long timeStamp;

    public TABLE_USER_PROFILES() {
    }

    public TABLE_USER_PROFILES(Long _id) {
        this._id = _id;
    }

    public TABLE_USER_PROFILES(Long _id, Integer userProfId, Integer userProfUsrId, Integer userProfUsrTypeId, Integer userStateID, Long timeStamp) {
        this._id = _id;
        this.userProfId = userProfId;
        this.userProfUsrId = userProfUsrId;
        this.userProfUsrTypeId = userProfUsrTypeId;
        this.userStateID = userStateID;
        this.timeStamp = timeStamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getUserProfId() {
        return userProfId;
    }

    public void setUserProfId(Integer userProfId) {
        this.userProfId = userProfId;
    }

    public Integer getUserProfUsrId() {
        return userProfUsrId;
    }

    public void setUserProfUsrId(Integer userProfUsrId) {
        this.userProfUsrId = userProfUsrId;
    }

    public Integer getUserProfUsrTypeId() {
        return userProfUsrTypeId;
    }

    public void setUserProfUsrTypeId(Integer userProfUsrTypeId) {
        this.userProfUsrTypeId = userProfUsrTypeId;
    }

    public Integer getUserStateID() {
        return userStateID;
    }

    public void setUserStateID(Integer userStateID) {
        this.userStateID = userStateID;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
