package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__SPEAKER.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_SPEAKER {

    private Long _id;

    @SerializedName("speaker_id")
    @Expose
    private Integer speakerId;

    @SerializedName("speaker_usrid")
    @Expose
    private Integer speakerUserId;

    @SerializedName("speaker_typid")
    @Expose
    private Integer speakerTypeId;

    @SerializedName("speaker_typname")
    @Expose
    private String speakerTypeName;

    @SerializedName("speaker_image")
    @Expose
    private String speakerImage;

    @SerializedName("speaker_name")
    @Expose
    private String speakerName;

    @SerializedName("speaker_mobile")
    @Expose
    private String speakerMobileNo;

    @SerializedName("speaker_timestamp")
    @Expose
    private Long timeStamp;

    public TABLE_SPEAKER() {
    }

    public TABLE_SPEAKER(Long _id) {
        this._id = _id;
    }

    public TABLE_SPEAKER(Long _id, Integer speakerId, Integer speakerUserId, Integer speakerTypeId, String speakerTypeName, String speakerImage, String speakerName, String speakerMobileNo, Long timeStamp) {
        this._id = _id;
        this.speakerId = speakerId;
        this.speakerUserId = speakerUserId;
        this.speakerTypeId = speakerTypeId;
        this.speakerTypeName = speakerTypeName;
        this.speakerImage = speakerImage;
        this.speakerName = speakerName;
        this.speakerMobileNo = speakerMobileNo;
        this.timeStamp = timeStamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getSpeakerId() {
        return speakerId;
    }

    public void setSpeakerId(Integer speakerId) {
        this.speakerId = speakerId;
    }

    public Integer getSpeakerUserId() {
        return speakerUserId;
    }

    public void setSpeakerUserId(Integer speakerUserId) {
        this.speakerUserId = speakerUserId;
    }

    public Integer getSpeakerTypeId() {
        return speakerTypeId;
    }

    public void setSpeakerTypeId(Integer speakerTypeId) {
        this.speakerTypeId = speakerTypeId;
    }

    public String getSpeakerTypeName() {
        return speakerTypeName;
    }

    public void setSpeakerTypeName(String speakerTypeName) {
        this.speakerTypeName = speakerTypeName;
    }

    public String getSpeakerImage() {
        return speakerImage;
    }

    public void setSpeakerImage(String speakerImage) {
        this.speakerImage = speakerImage;
    }

    public String getSpeakerName() {
        return speakerName;
    }

    public void setSpeakerName(String speakerName) {
        this.speakerName = speakerName;
    }

    public String getSpeakerMobileNo() {
        return speakerMobileNo;
    }

    public void setSpeakerMobileNo(String speakerMobileNo) {
        this.speakerMobileNo = speakerMobileNo;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
