package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__EVENT__TASK.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_EVENT_TASK {

    private Long _id;

    @SerializedName("et_id")
    @Expose
    private Integer etId;

    @SerializedName("et_tc_id")
    @Expose
    private Integer etTcId;

    @SerializedName("et_event_id")
    @Expose
    private Integer etEventId;

    @SerializedName("et_start_time")
    @Expose
    private Long et_StartTime;

    @SerializedName("et_end_time")
    @Expose
    private Long et_End_Time;

    @SerializedName("et_evnt_name")
    @Expose
    private String et_evnt_name;

    @SerializedName("et_status")
    @Expose
    private Integer etStatus;

    @SerializedName("et_timestamp")
    @Expose
    private Long timeStamp;

    @SerializedName("evnt_image")
    @Expose
    private String evntImage;



    public TABLE_EVENT_TASK() {
    }

    public TABLE_EVENT_TASK(Long _id) {
        this._id = _id;
    }

    public TABLE_EVENT_TASK(Long _id, Integer etId, Integer etTcId, Integer etEventId, Long et_StartTime, Long et_End_Time, String et_evnt_name, Integer etStatus, Long timeStamp, String evntImage) {
        this._id = _id;
        this.etId = etId;
        this.etTcId = etTcId;
        this.etEventId = etEventId;
        this.et_StartTime = et_StartTime;
        this.et_End_Time = et_End_Time;
        this.et_evnt_name = et_evnt_name;
        this.etStatus = etStatus;
        this.timeStamp = timeStamp;
        this.evntImage = evntImage;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getEtId() {
        return etId;
    }

    public void setEtId(Integer etId) {
        this.etId = etId;
    }

    public Integer getEtTcId() {
        return etTcId;
    }

    public void setEtTcId(Integer etTcId) {
        this.etTcId = etTcId;
    }

    public Integer getEtEventId() {
        return etEventId;
    }

    public void setEtEventId(Integer etEventId) {
        this.etEventId = etEventId;
    }

    public Long getEt_StartTime() {
        return et_StartTime;
    }

    public void setEt_StartTime(Long et_StartTime) {
        this.et_StartTime = et_StartTime;
    }

    public Long getEt_End_Time() {
        return et_End_Time;
    }

    public void setEt_End_Time(Long et_End_Time) {
        this.et_End_Time = et_End_Time;
    }

    public String getEt_evnt_name() {
        return et_evnt_name;
    }

    public void setEt_evnt_name(String et_evnt_name) {
        this.et_evnt_name = et_evnt_name;
    }

    public Integer getEtStatus() {
        return etStatus;
    }

    public void setEtStatus(Integer etStatus) {
        this.etStatus = etStatus;
    }

    public String getEvntImage() {
        return evntImage;
    }

    public void setEvntImage(String evntImage) {
        this.evntImage = evntImage;
    }



    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
