package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__EVENT__SPEAKER.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_EVENT_SPEAKER {

    private Long _id;

    @SerializedName("es_id")
    @Expose
    private Integer ep_Id;

    @SerializedName("es_speaker_id")
    @Expose
    private Integer epSpeakerId;

    @SerializedName("es_event_id")
    @Expose
    private Integer epEventId;

    @SerializedName("es_topic")
    @Expose
    private String epTopic;

    @SerializedName("es_desc")
    @Expose
    private String epSpeakerDesc;
    private Integer epTaId;
    private Integer epStatus;
    private Long timeStamp;

    public TABLE_EVENT_SPEAKER() {
    }

    public TABLE_EVENT_SPEAKER(Long _id) {
        this._id = _id;
    }

    public TABLE_EVENT_SPEAKER(Long _id, Integer ep_Id, Integer epSpeakerId, Integer epEventId, String epTopic, String epSpeakerDesc, Integer epTaId, Integer epStatus, Long timeStamp) {
        this._id = _id;
        this.ep_Id = ep_Id;
        this.epSpeakerId = epSpeakerId;
        this.epEventId = epEventId;
        this.epTopic = epTopic;
        this.epSpeakerDesc = epSpeakerDesc;
        this.epTaId = epTaId;
        this.epStatus = epStatus;
        this.timeStamp = timeStamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getEp_Id() {
        return ep_Id;
    }

    public void setEp_Id(Integer ep_Id) {
        this.ep_Id = ep_Id;
    }

    public Integer getEpSpeakerId() {
        return epSpeakerId;
    }

    public void setEpSpeakerId(Integer epSpeakerId) {
        this.epSpeakerId = epSpeakerId;
    }

    public Integer getEpEventId() {
        return epEventId;
    }

    public void setEpEventId(Integer epEventId) {
        this.epEventId = epEventId;
    }

    public String getEpTopic() {
        return epTopic;
    }

    public void setEpTopic(String epTopic) {
        this.epTopic = epTopic;
    }

    public String getEpSpeakerDesc() {
        return epSpeakerDesc;
    }

    public void setEpSpeakerDesc(String epSpeakerDesc) {
        this.epSpeakerDesc = epSpeakerDesc;
    }

    public Integer getEpTaId() {
        return epTaId;
    }

    public void setEpTaId(Integer epTaId) {
        this.epTaId = epTaId;
    }

    public Integer getEpStatus() {
        return epStatus;
    }

    public void setEpStatus(Integer epStatus) {
        this.epStatus = epStatus;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
