package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table TABLE__LOCATION__AREA.
 */
public class TABLE_LOCATION_AREA {

    private Long id;
    @SerializedName("locarea_id")
    @Expose
    private Integer locarea_id;
    @SerializedName("locarea_user_id")
    @Expose
    private Integer locarea_user_id;
    @SerializedName("locarea_dist_id")
    @Expose
    private Integer locarea_dist_id;
    @SerializedName("locarea_status_id")
    @Expose
    private Integer locarea_status_id;
    @SerializedName("locarea_name")
    @Expose
    private String locarea_name;

    public TABLE_LOCATION_AREA() {
    }

    public TABLE_LOCATION_AREA(Long id) {
        this.id = id;
    }

    public TABLE_LOCATION_AREA(Long id, Integer locarea_id, Integer locarea_user_id, Integer locarea_dist_id, Integer locarea_status_id, String locarea_name) {
        this.id = id;
        this.locarea_id = locarea_id;
        this.locarea_user_id = locarea_user_id;
        this.locarea_dist_id = locarea_dist_id;
        this.locarea_status_id = locarea_status_id;
        this.locarea_name = locarea_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLocarea_id() {
        return locarea_id;
    }

    public void setLocarea_id(Integer locarea_id) {
        this.locarea_id = locarea_id;
    }

    public Integer getLocarea_user_id() {
        return locarea_user_id;
    }

    public void setLocarea_user_id(Integer locarea_user_id) {
        this.locarea_user_id = locarea_user_id;
    }

    public Integer getLocarea_dist_id() {
        return locarea_dist_id;
    }

    public void setLocarea_dist_id(Integer locarea_dist_id) {
        this.locarea_dist_id = locarea_dist_id;
    }

    public Integer getLocarea_status_id() {
        return locarea_status_id;
    }

    public void setLocarea_status_id(Integer locarea_status_id) {
        this.locarea_status_id = locarea_status_id;
    }

    public String getLocarea_name() {
        return locarea_name;
    }

    public void setLocarea_name(String locarea_name) {
        this.locarea_name = locarea_name;
    }
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
