package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__STATUS.
 */
public class TABLE_STATUS {

    private Long _id;
    private Integer statusId;
    private String statusName;

    public TABLE_STATUS() {
    }

    public TABLE_STATUS(Long _id) {
        this._id = _id;
    }

    public TABLE_STATUS(Long _id, Integer statusId, String statusName) {
        this._id = _id;
        this.statusId = statusId;
        this.statusName = statusName;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getStatusId() {
        return statusId;
    }

    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

}
