package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__TASK.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_TASK {

    private Long _id;

    @SerializedName("task_id")
    @Expose
    private Integer tskId;

    @SerializedName("task_name")
    @Expose
    private String tskName;

    @SerializedName("task_status")
    @Expose
    private Integer tskStatusId;

    @SerializedName("task_timestamp")
    @Expose
    private Long timeStamp;

    public TABLE_TASK() {
    }

    public TABLE_TASK(Long _id) {
        this._id = _id;
    }

    public TABLE_TASK(Long _id, Integer tskId, String tskName, Integer tskStatusId, Long timeStamp) {
        this._id = _id;
        this.tskId = tskId;
        this.tskName = tskName;
        this.tskStatusId = tskStatusId;
        this.timeStamp = timeStamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getTskId() {
        return tskId;
    }

    public void setTskId(Integer tskId) {
        this.tskId = tskId;
    }

    public String getTskName() {
        return tskName;
    }

    public void setTskName(String tskName) {
        this.tskName = tskName;
    }

    public Integer getTskStatusId() {
        return tskStatusId;
    }

    public void setTskStatusId(Integer tskStatusId) {
        this.tskStatusId = tskStatusId;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
