package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__TASK__CATEGORY.
 */

import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_TASK_CATEGORY {

    private Long _id;

    @SerializedName("taskcat_catid")
    @Expose
    private Integer tcId;

    @SerializedName("taskcat_id")
    @Expose
    private Integer tcTskId;

    @SerializedName("taskcat_status")
    @Expose
    private Integer tcCatId;

    @SerializedName("taskcat_taskid")
    @Expose
    private Integer tcStatusId;

    @SerializedName("taskcat_timestamp")
    @Expose
    private Long timeStamp;

    public TABLE_TASK_CATEGORY() {
    }

    public TABLE_TASK_CATEGORY(Long _id) {
        this._id = _id;
    }

    public TABLE_TASK_CATEGORY(Long _id, Integer tcId, Integer tcTskId, Integer tcCatId, Integer tcStatusId, Long timeStamp) {
        this._id = _id;
        this.tcId = tcId;
        this.tcTskId = tcTskId;
        this.tcCatId = tcCatId;
        this.tcStatusId = tcStatusId;
        this.timeStamp = timeStamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getTcId() {
        return tcId;
    }

    public void setTcId(Integer tcId) {
        this.tcId = tcId;
    }

    public Integer getTcTskId() {
        return tcTskId;
    }

    public void setTcTskId(Integer tcTskId) {
        this.tcTskId = tcTskId;
    }

    public Integer getTcCatId() {
        return tcCatId;
    }

    public void setTcCatId(Integer tcCatId) {
        this.tcCatId = tcCatId;
    }

    public Integer getTcStatusId() {
        return tcStatusId;
    }

    public void setTcStatusId(Integer tcStatusId) {
        this.tcStatusId = tcStatusId;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
