package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.Gson;

/**
 * Entity mapped to table TABLE__TASK__ALLOTMENT.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_TASK_ALLOTMENT {

    private Long _id;

    @SerializedName("ta_id")
    @Expose
    private Integer taId;

    @SerializedName("ta_et_id")
    @Expose
    private Integer taEtId;

    @SerializedName("ta_user_id")
    @Expose
    private Integer taUsrId;

    @SerializedName("ta_alt_time")
    @Expose
    private Long taStartTime;

    @SerializedName("ta_end_time")
    @Expose
    private Long taEndTime;

    @SerializedName("ta_confirm")
    @Expose
    private String taConfirm;

    @SerializedName("ta_staff_id")
    @Expose
    private Integer taStaffId;

    @SerializedName("ta_staffname")
    @Expose
    private String taStaffName;

    @SerializedName("ta_status")
    @Expose
    private Integer taStatusId;

    @SerializedName("ta_timestamp")
    @Expose
    private Long timeStamp;

    @SerializedName("ta_start_date")
    @Expose
    private Long taStartDate;

    @SerializedName("ta_end_date")
    @Expose
    private Long taEndDate;

    @SerializedName("ta_user_name")
    @Expose
    private String usrName;

    @SerializedName("ta_user_mobile")
    @Expose
    private String usrMobile;

    @SerializedName("ta_user_image")
    @Expose
    private String usrImage;

    @SerializedName("ta_usertype_id")
    @Expose
    private Integer taUsertypeId;

    public Integer getTaUsertypeId() {
        return taUsertypeId;
    }

    public void setTaUsertypeId(Integer taUsertypeId) {
        this.taUsertypeId = taUsertypeId;
    }



    public TABLE_TASK_ALLOTMENT() {
    }

    public TABLE_TASK_ALLOTMENT(Long _id) {
        this._id = _id;
    }

    public TABLE_TASK_ALLOTMENT(Long _id, Integer taId, Integer taEtId, Integer taUsrId, Long taStartTime, Long taEndTime, String taConfirm, Integer taStaffId, String taStaffName, Integer taStatusId, Long timeStamp, Long taStartDate, Long taEndDate, String usrName, String usrMobile, String usrImage, Integer taUsertypeId) {
        this._id = _id;
        this.taId = taId;
        this.taEtId = taEtId;
        this.taUsrId = taUsrId;
        this.taStartTime = taStartTime;
        this.taEndTime = taEndTime;
        this.taConfirm = taConfirm;
        this.taStaffId = taStaffId;
        this.taStaffName = taStaffName;
        this.taStatusId = taStatusId;
        this.timeStamp = timeStamp;
        this.taStartDate = taStartDate;
        this.taEndDate = taEndDate;
        this.usrName = usrName;
        this.usrMobile = usrMobile;
        this.usrImage = usrImage;
        this.taUsertypeId = taUsertypeId;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getTaId() {
        return taId;
    }

    public void setTaId(Integer taId) {
        this.taId = taId;
    }

    public Integer getTaEtId() {
        return taEtId;
    }

    public void setTaEtId(Integer taEtId) {
        this.taEtId = taEtId;
    }

    public Integer getTaUsrId() {
        return taUsrId;
    }

    public void setTaUsrId(Integer taUsrId) {
        this.taUsrId = taUsrId;
    }

    public Long getTaStartTime() {
        return taStartTime;
    }

    public void setTaStartTime(Long taStartTime) {
        this.taStartTime = taStartTime;
    }

    public Long getTaEndTime() {
        return taEndTime;
    }

    public void setTaEndTime(Long taEndTime) {
        this.taEndTime = taEndTime;
    }

    public String getTaConfirm() {
        return taConfirm;
    }

    public void setTaConfirm(String taConfirm) {
        this.taConfirm = taConfirm;
    }

    public Integer getTaStaffId() {
        return taStaffId;
    }

    public void setTaStaffId(Integer taStaffId) {
        this.taStaffId = taStaffId;
    }

    public String getTaStaffName() {
        return taStaffName;
    }

    public void setTaStaffName(String taStaffName) {
        this.taStaffName = taStaffName;
    }

    public Integer getTaStatusId() {
        return taStatusId;
    }

    public void setTaStatusId(Integer taStatusId) {
        this.taStatusId = taStatusId;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getTaStartDate() {
        return taStartDate;
    }
    public void setTaStartDate(Long taStartDate) {
        this.taStartDate = taStartDate;
    }

    public Long getTaEndDate() {
        return taEndDate;
    }

    public void setTaEndDate(Long taEndDate) {
        this.taEndDate = taEndDate;
    }

    public String getUsrName() {
        return usrName;
    }

    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }

    public String getUsrMobile() {
        return usrMobile;
    }

    public void setUsrMobile(String usrMobile) {
        this.usrMobile = usrMobile;
    }

    public String getUsrImage() {
        return usrImage;
    }

    public void setUsrImage(String usrImage) {
        this.usrImage = usrImage;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
