package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table TABLE__DISTRICT.
 */
public class TABLE_DISTRICT {

    private Long id;
    @SerializedName("dist_id")
    @Expose
    private Integer dist_id;
    @SerializedName("dist_st_id")
    @Expose
    private Integer dist_st_id;
    @SerializedName("st_name")
    @Expose
    private Integer dist_status_id;
    @SerializedName("dist_name")
    @Expose
    private String dist_name;

    public TABLE_DISTRICT() {
    }

    public TABLE_DISTRICT(Long id) {
        this.id = id;
    }

    public TABLE_DISTRICT(Long id, Integer dist_id, Integer dist_st_id, Integer dist_status_id, String dist_name) {
        this.id = id;
        this.dist_id = dist_id;
        this.dist_st_id = dist_st_id;
        this.dist_status_id = dist_status_id;
        this.dist_name = dist_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDist_id() {
        return dist_id;
    }

    public void setDist_id(Integer dist_id) {
        this.dist_id = dist_id;
    }

    public Integer getDist_st_id() {
        return dist_st_id;
    }

    public void setDist_st_id(Integer dist_st_id) {
        this.dist_st_id = dist_st_id;
    }

    public Integer getDist_status_id() {
        return dist_status_id;
    }

    public void setDist_status_id(Integer dist_status_id) {
        this.dist_status_id = dist_status_id;
    }

    public String getDist_name() {
        return dist_name;
    }

    public void setDist_name(String dist_name) {
        this.dist_name = dist_name;
    }
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
