package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__EVENT.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_EVENT {

    private Long _id;

    @SerializedName("event_id")
    @Expose
    private Integer eventId;

    @SerializedName("event_name")
    @Expose
    private String eventName;

    @SerializedName("event_location")
    @Expose
    private String eventLocation;

    @SerializedName("event_date")
    @Expose
    private Long eventDate;

    @SerializedName("event_time")
    @Expose
    private Long eventTime;

    @SerializedName("event_desc")
    @Expose
    private String eventDesc;

    @SerializedName("event_image")
    @Expose
    private String eventImage;

    @SerializedName("event_status")
    @Expose
    private Integer eventStatus;

    @SerializedName("event_locareaid")
    @Expose
    private Integer eventLocareaid;

    public TABLE_EVENT() {
    }

    public TABLE_EVENT(Long _id) {
        this._id = _id;
    }

    public TABLE_EVENT(Long _id, Integer eventId, String eventName, String eventLocation, Long eventDate, Long eventTime, String eventDesc, String eventImage, Integer eventStatus, Integer eventLocareaid) {
        this._id = _id;
        this.eventId = eventId;
        this.eventName = eventName;
        this.eventLocation = eventLocation;
        this.eventDate = eventDate;
        this.eventTime = eventTime;
        this.eventDesc = eventDesc;
        this.eventImage = eventImage;
        this.eventStatus = eventStatus;
        this.eventLocareaid = eventLocareaid;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getEventId() {
        return eventId;
    }

    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    public String getEventName() {
        return eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public String getEventLocation() {
        return eventLocation;
    }

    public void setEventLocation(String eventLocation) {
        this.eventLocation = eventLocation;
    }

    public Long getEventDate() {
        return eventDate;
    }

    public void setEventDate(Long eventDate) {
        this.eventDate = eventDate;
    }

    public Long getEventTime() {
        return eventTime;
    }

    public void setEventTime(Long eventTime) {
        this.eventTime = eventTime;
    }

    public String getEventDesc() {
        return eventDesc;
    }

    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }

    public String getEventImage() {
        return eventImage;
    }

    public void setEventImage(String eventImage) {
        this.eventImage = eventImage;
    }

    public Integer getEventStatus() {
        return eventStatus;
    }

    public void setEventStatus(Integer eventStatus) {
        this.eventStatus = eventStatus;
    }
    public Integer getEventLocareaid() {
        return eventLocareaid;
    }

    public void setEventLocareaid(Integer eventLocareaid) {
        this.eventLocareaid = eventLocareaid;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
