package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__USER__TYPE.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_USER_TYPE {

    private Long _id;

    @SerializedName("ustype_id")
    @Expose
    private Integer usrTypeId;

    @SerializedName("ustype_name")
    @Expose
    private String usrTypeName;

    @SerializedName("ustype_timestamp")
    @Expose
    private Long timeStamp;

    public TABLE_USER_TYPE() {
    }

    public TABLE_USER_TYPE(Long _id) {
        this._id = _id;
    }

    public TABLE_USER_TYPE(Long _id, Integer usrTypeId, String usrTypeName, Long timeStamp) {
        this._id = _id;
        this.usrTypeId = usrTypeId;
        this.usrTypeName = usrTypeName;
        this.timeStamp = timeStamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getUsrTypeId() {
        return usrTypeId;
    }

    public void setUsrTypeId(Integer usrTypeId) {
        this.usrTypeId = usrTypeId;
    }

    public String getUsrTypeName() {
        return usrTypeName;
    }

    public void setUsrTypeName(String usrTypeName) {
        this.usrTypeName = usrTypeName;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }


}
