package com.abyz.infotech.warroomapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLE__CATEGORY.
 */
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
public class TABLE_CATEGORY {

    private Long _id;

    @SerializedName("cat_id")
    @Expose
    private Integer catId;

    @SerializedName("cat_name")
    @Expose
    private String catName;

    @SerializedName("cat_status")
    @Expose
    private Integer catStatusId;

    @SerializedName("cat_timestamp")
    @Expose
    private Long timeStamp;

    public TABLE_CATEGORY() {
    }

    public TABLE_CATEGORY(Long _id) {
        this._id = _id;
    }

    public TABLE_CATEGORY(Long _id, Integer catId, String catName, Integer catStatusId, Long timeStamp) {
        this._id = _id;
        this.catId = catId;
        this.catName = catName;
        this.catStatusId = catStatusId;
        this.timeStamp = timeStamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getCatId() {
        return catId;
    }

    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    public String getCatName() {
        return catName;
    }

    public void setCatName(String catName) {
        this.catName = catName;
    }

    public Integer getCatStatusId() {
        return catStatusId;
    }

    public void setCatStatusId(Integer catStatusId) {
        this.catStatusId = catStatusId;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
